### ISSUE TITLE
Hawk authentication docs

### ISSUE THREAD

**Issue by torotil** [marselester/flask-api-utils#2]
Hi and thanks for publishing this extension.

I guess I'd need some more information on how the hawk-authentication is supposed to work. I have the basic example up and running. To do something useful I must have answers to at least the following questions:
- How can I keep track of the currently authenticated "user"?
- How can I write unit-tests for functionality that depends on having an authenticated user?

Any suggestions?

**Comment by marselester** [comment]
Hi, thanks for your kind words.

As far as I understand, you're asking about [current_user](https://flask-login.readthedocs.org/en/latest/#flask.ext.login.current_user) like functionality. Unfortunately I have not had a chance to implement that.

For testing [this example](https://github.com/marselester/api-example-based-on-flask/blob/master/tests/v3/test_views.py) might help.

**Comment by torotil** [comment]
Thanks again for the pointers. It seems that I'll end up implementing something like current_user for API-keys.
