### ISSUE TITLE
Hawk: Support for application/x-www-form-urlencoded

### ISSUE THREAD

**Issue by torotil** [marselester/flask-api-utils#3]
The current implementation of Hawk works fine for application/json, but it doesn't work for urlencoded post data.

The reason is that (at this time in the request) the form-encoded data can only be accessed in request.form or request.content - while request.data is empty.

Maybe it would be more robust to move the signature checking into a WSGI-middleware and then access the results later on in the decorators.

**Comment by torotil** [comment]
`request.get_data()` might be better still.

**Comment by marselester** [comment]
I replaced it by `request.get_data()`, thanks!

**Comment by torotil** [comment]
I guess we can close this then.
