### ISSUE TITLE
Bypass hawk authentication if config['TESTING'] is set.

### ISSUE THREAD

**Issue by torotil** [marselester/flask-api-utils#4]
For writing tests it might be convenient to disable the authentication wrapper if the TESTING config-flag is set. Otherwise tests must implement a fully-fledged Hawk-Client.

This is also something Flask-Login does. To quote the documentation for `@login_required`:

> It can be convenient to globally turn off authentication when unit testing. To enable this, if either of the application configuration variables `LOGIN_DISABLED` or `TESTING` is set to `True`, this decorator will be ignored.

**Comment by marselester** [comment]
Hi! Thanks for the idea, I'll implement that.

**Comment by marselester** [comment]
done

**Comment by torotil** [comment]
Great! Thanks a lot.
